<?php
/**
 * BookYourShow - Central 50 Indian Cities List
 * Used across: register, operator-register, operator-dashboard, header
 * Alphabetically sorted as per user specification.
 */
define('BYS_CITIES', [
    'Agra',
    'Ahmedabad',
    'Allahabad',
    'Amritsar',
    'Aurangabad',
    'Bangalore',
    'Bhopal',
    'Chandigarh',
    'Chennai',
    'Coimbatore',
    'Delhi',
    'Dhanbad',
    'Faridabad',
    'Ghaziabad',
    'Guwahati',
    'Gwalior',
    'Howrah',
    'Hubli-Dharwad',
    'Hyderabad',
    'Indore',
    'Jabalpur',
    'Jaipur',
    'Jodhpur',
    'Kalyan-Dombivali',
    'Kanpur',
    'Kolkata',
    'Kota',
    'Lucknow',
    'Ludhiana',
    'Madurai',
    'Meerut',
    'Mumbai',
    'Nagpur',
    'Nashik',
    'Navi Mumbai',
    'Patna',
    'Pimpri-Chinchwad',
    'Pune',
    'Raipur',
    'Rajkot',
    'Ranchi',
    'Solapur',
    'Srinagar',
    'Surat',
    'Thane',
    'Vadodara',
    'Varanasi',
    'Vasai-Virar',
    'Vijayawada',
    'Visakhapatnam',
]);
